# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Flantiers: une semaine, un flan"
email: hello@flantiers.fr
description: >- # this means to ignore newlines until "baseurl:"
  Flantiers goûte les meilleurs flans pour vous.
baseurl: "" # the subpath of your site, e.g. /blog
logo: /assets/images/main_flan.jpg
url: "https://www.flantiers.heroku.com" # the base hostname & protocol for your site, e.g. http://example.com
author: "Flantiers"
twitter:
  username: Flantiers
  card: summary
social:
  name: Flantiers
  links:
    - https://twitter.com/Flantiers
    - https://github.com/Flantiers/flantiers-website
github_username:  https://github.com/Flantiers/flantiers-website

collections:
  articles:
    output: true

# Remove .html extension in pages
permalink: pretty

# Default layouts
defaults:
  - scope:
      path: ""
      type: "articles"
    values:
      layout: "article"
  - scope:
      path: ""
    values:
      layout: "default"

sass:
  load_paths:
    - _sass
    - node_modules

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin

# jekyll-multiple-languages-plugin settings:
languages: ["fr"]

exclude_from_localizations: [ "javascript", "images", "css", "scripts", "favicon.ico" ]

include:
  - node_modules/axios/dist/axios.min.js
  - node_modules/axios/dist/axios.min.map
  - node_modules/@popperjs/core/dist/umd/popper.min.js
  - node_modules/@popperjs/core/dist/umd/popper.min.js.map
  - node_modules/bootstrap/dist/js/bootstrap.min.js
  - node_modules/bootstrap/dist/js/bootstrap.min.js.map
  - node_modules/mdb-ui-kit/js/mdb.min.js
  - node_modules/mdb-ui-kit/js/mdb.min.js.map
  - node_modules/@fortawesome/fontawesome-free/js/all.js

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
